name: Report Outcome

on: repository_dispatch

jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: echo ${{ github.event.action }}
      - run: echo ${{ secrets.GITHUB_TOKEN }}
      - name: Run zbctl
        run: |
          docker run  --env ZEEBE_ADDRESS='${{ secrets.ZEEBE_ADDRESS }}' --env ZEEBE_CLIENT_ID='${{ secrets.ZEEBE_CLIENT_ID }}' --env ZEEBE_CLIENT_SECRET='${{ secrets.ZEEBE_CLIENT_SECRET }}' --env ZEEBE_AUTHORIZATION_SERVER_URL='${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}' sitapati/zbctl status
      - name: Create Zeebe Workflow
        uses: jwulf/zeebe-action@master
        with:
          zeebe_address: ${{ secrets.ZEEBE_ADDRESS }}
          zeebe_client_id: ${{ secrets.ZEEBE_CLIENT_ID }}
          zeebe_authorization_server_url: ${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}
          zeebe_client_secret: ${{ secrets.ZEEBE_CLIENT_SECRET }}
          operation: createWorkflowInstance
          bpmn_process_id: throw-test
          variables: "{event: ${{ github.event.action }} }"
