name: Report Outcome

on: repository_dispatch

jobs:
  report:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: echo ${{ github.event.action }}
      - name: Run zbctl
        run: |
          docker run  --env ZEEBE_ADDRESS='${{ secrets.ZEEBE_ADDRESS }}' --env ZEEBE_CLIENT_ID='${{ secrets.ZEEBE_CLIENT_ID }}' --env ZEEBE_CLIENT_SECRET='${{ secrets.ZEEBE_CLIENT_SECRET }}' --env ZEEBE_AUTHORIZATION_SERVER_URL='${{ secrets.ZEEBE_AUTHORIZATION_SERVER_URL }}' sitapati/zbctl status
